version: '3.8'
services:
  api:
    build:
      context: ./backend/ContactManagerAPI
      dockerfile: Dockerfile
    ports:
      - "7295:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7295
      - ConnectionStrings__SqlServerConnection=Server=sqlserver;Database=ContactManager;User=sa;Password=Password123
      - Token__Key=GlTJa5Gd5KNF0B2GdzW2kciL6SjS9NRe
      - Token__Issuer=https://localhost:7295/
      - Token__Audience=https://localhost:7295/

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"